#!/bin/sh
_todo_all() {
  _todo_list
}

_todo_list() {
  project="$1"
  if [ "$project" ]; then
    shift
  else
    project=*
  fi
  awk -f $TODOS_PATH/lib/list.awk $TODOS_DIR/$project 2>/dev/null
}

_todo_today() {
  project="$1"
  if [ "$project" ]; then
    shift
  else
    project=*
  fi
  awk -f $TODOS_PATH/lib/today.awk $TODOS_DIR/$project 2>/dev/null
}

_todo_bricks() {
  project="$1"
  if [ "$project" ]; then
    shift
  else
    project=*
  fi
  awk -f $TODOS_PATH/lib/bricks.awk $TODOS_DIR/$project 2>/dev/null
}

action="$1"
[ "$action" ] && shift
case "${action}" in
  list) _todo_list "$@" ;;
  today) _todo_today "$@" ;;
  bricks) _todo_bricks "$@" ;;
  *) _todo_all ;;
esac
